#!/bin/bash

# Compile pascal source with win32 compiler using wine
# Usage: fpc_win input_file.pas [-o<output_file.exe>]
# 
# Author: Alexander Gudulin <alexandr.gudulin@gmail.com>

FPC_EXE="$HOME/.wine/drive_c/FPC/2.4.4/bin/i386-win32/fpc.exe"

function show_help {
	echo "Usage:  fpc_win input_file.pas"
	echo "-o<x>   Change the name of the executable produced to <x>"
}

if [ $1 ]; then
	in_filename="_$1"
	out_filename="_$1.exe"

	if [ "${1:0:1}" == "-" ]; then
		if [ "${1:1}" == "help" ]; then
			show_help
		fi
		exit
	fi

	if [ $2 ]; then
		if [ "${2:0:2}" == "-o" ]; then
			out_filename="${2:2}"
		fi
	fi
	`iconv -f utf-8 -t cp866 $1>$in_filename`
	`wine $FPC_EXE $in_filename -o$out_filename`
else
	show_help
fi